name: run full su6 checks
on:
  push:
    branches:
      - master
jobs:
  check-310:
    name: Check with `su6 all`
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies
      - run: pip install .[dev]
      - run: su6 all --coverage 100 --stop-after-first-failure
  check-311:
    name: Check with `su6 all`
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip' # caching pip dependencies
      - run: pip install .[dev]
      - run: su6 all --coverage 100 --stop-after-first-failure
  check-312:
    name: Check with `su6 all`
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip' # caching pip dependencies
      - run: pip install .[dev]
      - run: su6 all --coverage 100 --stop-after-first-failure
